// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bingo.sql

package repo

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBingo = `-- name: CreateBingo :one
INSERT INTO bingo (title, description, cells, created_by_email) VALUES ($1, $2, $3, $4) RETURNING id, title, description, cells, created_at, updated_at, img_center, img_bg, card_img_preview, created_by_email
`

type CreateBingoParams struct {
	Title          string          `json:"title"`
	Description    pgtype.Text     `json:"description"`
	Cells          json.RawMessage `json:"cells"`
	CreatedByEmail pgtype.Text     `json:"created_by_email"`
}

func (q *Queries) CreateBingo(ctx context.Context, arg CreateBingoParams) (Bingo, error) {
	row := q.db.QueryRow(ctx, createBingo,
		arg.Title,
		arg.Description,
		arg.Cells,
		arg.CreatedByEmail,
	)
	var i Bingo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Cells,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImgCenter,
		&i.ImgBg,
		&i.CardImgPreview,
		&i.CreatedByEmail,
	)
	return i, err
}

const deleteBingo = `-- name: DeleteBingo :exec
DELETE FROM bingo WHERE id = $1
`

func (q *Queries) DeleteBingo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBingo, id)
	return err
}

const getBingo = `-- name: GetBingo :many
SELECT id, title, description, cells, created_at, updated_at, img_center, img_bg, card_img_preview, created_by_email FROM bingo
`

func (q *Queries) GetBingo(ctx context.Context) ([]Bingo, error) {
	rows, err := q.db.Query(ctx, getBingo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bingo
	for rows.Next() {
		var i Bingo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Cells,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImgCenter,
			&i.ImgBg,
			&i.CardImgPreview,
			&i.CreatedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBingoByEmail = `-- name: GetBingoByEmail :many
SELECT id, title, description, cells, created_at, updated_at, img_center, img_bg, card_img_preview, created_by_email FROM bingo WHERE created_by_email = $1
`

func (q *Queries) GetBingoByEmail(ctx context.Context, createdByEmail pgtype.Text) ([]Bingo, error) {
	rows, err := q.db.Query(ctx, getBingoByEmail, createdByEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bingo
	for rows.Next() {
		var i Bingo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Cells,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImgCenter,
			&i.ImgBg,
			&i.CardImgPreview,
			&i.CreatedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBingoById = `-- name: GetBingoById :one
SELECT id, title, description, cells, created_at, updated_at, img_center, img_bg, card_img_preview, created_by_email FROM bingo WHERE id = $1
`

func (q *Queries) GetBingoById(ctx context.Context, id int64) (Bingo, error) {
	row := q.db.QueryRow(ctx, getBingoById, id)
	var i Bingo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Cells,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImgCenter,
		&i.ImgBg,
		&i.CardImgPreview,
		&i.CreatedByEmail,
	)
	return i, err
}

const updateBingo = `-- name: UpdateBingo :one
UPDATE bingo SET title = $2, description = $3, cells = $4 WHERE id = $1 RETURNING id, title, description, cells, created_at, updated_at, img_center, img_bg, card_img_preview, created_by_email
`

type UpdateBingoParams struct {
	ID          int64           `json:"id"`
	Title       string          `json:"title"`
	Description pgtype.Text     `json:"description"`
	Cells       json.RawMessage `json:"cells"`
}

func (q *Queries) UpdateBingo(ctx context.Context, arg UpdateBingoParams) (Bingo, error) {
	row := q.db.QueryRow(ctx, updateBingo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Cells,
	)
	var i Bingo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Cells,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImgCenter,
		&i.ImgBg,
		&i.CardImgPreview,
		&i.CreatedByEmail,
	)
	return i, err
}
