// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: genshin_details.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCharToProfile = `-- name: AddCharToProfile :one
WITH inserted AS (
    INSERT INTO profile_chars (
        acc_id, char_id, level, constellation,
        talent_na, talent_e, talent_q, notes
    ) VALUES (
        $1,
        (SELECT id FROM char_details cd WHERE cd.name = $2),
        $3, $4, $5, $6, $7, $8
    )
    RETURNING acc_id, char_id, level, constellation, talent_na, talent_e, talent_q, notes
)
SELECT
    profile_chars.acc_id, profile_chars.char_id, profile_chars.level, profile_chars.constellation, profile_chars.talent_na, profile_chars.talent_e, profile_chars.talent_q, profile_chars.notes,
    char_details.id, char_details.name, char_details.element_id, char_details.stars, char_details.icon, char_details.notes, char_details.created_at, char_details.updated_at,
    elements.id, elements.name, elements.icon_url
FROM inserted
JOIN profile_chars ON profile_chars.acc_id = inserted.acc_id AND profile_chars.char_id = inserted.char_id
JOIN char_details ON profile_chars.char_id = char_details.id
JOIN elements ON char_details.element_id = elements.id
`

type AddCharToProfileParams struct {
	AccID         int64       `json:"acc_id"`
	Name          string      `json:"name"`
	Level         int16       `json:"level"`
	Constellation int16       `json:"constellation"`
	TalentNa      int16       `json:"talent_na"`
	TalentE       int16       `json:"talent_e"`
	TalentQ       int16       `json:"talent_q"`
	Notes         pgtype.Text `json:"notes"`
}

type AddCharToProfileRow struct {
	ProfileChar ProfileChar `json:"profile_char"`
	CharDetail  CharDetail  `json:"char_detail"`
	Element     Element     `json:"element"`
}

func (q *Queries) AddCharToProfile(ctx context.Context, arg AddCharToProfileParams) (AddCharToProfileRow, error) {
	row := q.db.QueryRow(ctx, addCharToProfile,
		arg.AccID,
		arg.Name,
		arg.Level,
		arg.Constellation,
		arg.TalentNa,
		arg.TalentE,
		arg.TalentQ,
		arg.Notes,
	)
	var i AddCharToProfileRow
	err := row.Scan(
		&i.ProfileChar.AccID,
		&i.ProfileChar.CharID,
		&i.ProfileChar.Level,
		&i.ProfileChar.Constellation,
		&i.ProfileChar.TalentNa,
		&i.ProfileChar.TalentE,
		&i.ProfileChar.TalentQ,
		&i.ProfileChar.Notes,
		&i.CharDetail.ID,
		&i.CharDetail.Name,
		&i.CharDetail.ElementID,
		&i.CharDetail.Stars,
		&i.CharDetail.Icon,
		&i.CharDetail.Notes,
		&i.CharDetail.CreatedAt,
		&i.CharDetail.UpdatedAt,
		&i.Element.ID,
		&i.Element.Name,
		&i.Element.IconUrl,
	)
	return i, err
}

const createGenshinChar = `-- name: CreateGenshinChar :one
WITH created AS (
    INSERT INTO char_details (name, element_id, stars, icon, notes)
    VALUES(
        $1,
        (SELECT id FROM elements WHERE elements.name = $2),
        $3, $4, $5
    )
    RETURNING id, name, element_id, stars, icon, notes, created_at, updated_at
)
SELECT created.id, created.name, created.element_id, created.stars, created.icon, created.notes, created.created_at, created.updated_at, elements.name AS element_name
FROM created
JOIN elements ON created.element_id = elements.id
`

type CreateGenshinCharParams struct {
	Name        string      `json:"name"`
	ElementName string      `json:"element_name"`
	Stars       int16       `json:"stars"`
	Icon        []byte      `json:"icon"`
	Notes       pgtype.Text `json:"notes"`
}

type CreateGenshinCharRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	ElementID   int16              `json:"element_id"`
	Stars       int16              `json:"stars"`
	Icon        []byte             `json:"icon"`
	Notes       pgtype.Text        `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ElementName string             `json:"element_name"`
}

func (q *Queries) CreateGenshinChar(ctx context.Context, arg CreateGenshinCharParams) (CreateGenshinCharRow, error) {
	row := q.db.QueryRow(ctx, createGenshinChar,
		arg.Name,
		arg.ElementName,
		arg.Stars,
		arg.Icon,
		arg.Notes,
	)
	var i CreateGenshinCharRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ElementID,
		&i.Stars,
		&i.Icon,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ElementName,
	)
	return i, err
}

const createGenshinProfile = `-- name: CreateGenshinProfile :one
INSERT INTO genshin_profiles (name, notes)
VALUES ($1, $2) RETURNING id, name, notes, created_at, updated_at
`

type CreateGenshinProfileParams struct {
	Name  string      `json:"name"`
	Notes pgtype.Text `json:"notes"`
}

func (q *Queries) CreateGenshinProfile(ctx context.Context, arg CreateGenshinProfileParams) (GenshinProfile, error) {
	row := q.db.QueryRow(ctx, createGenshinProfile, arg.Name, arg.Notes)
	var i GenshinProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCharFromProfile = `-- name: DeleteCharFromProfile :exec
DELETE FROM profile_chars WHERE acc_id = $1 AND char_id = $2
`

type DeleteCharFromProfileParams struct {
	AccID  int64 `json:"acc_id"`
	CharID int64 `json:"char_id"`
}

func (q *Queries) DeleteCharFromProfile(ctx context.Context, arg DeleteCharFromProfileParams) error {
	_, err := q.db.Exec(ctx, deleteCharFromProfile, arg.AccID, arg.CharID)
	return err
}

const deleteGenshinChar = `-- name: DeleteGenshinChar :exec
DELETE FROM char_details WHERE id = $1
`

func (q *Queries) DeleteGenshinChar(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteGenshinChar, id)
	return err
}

const deleteGenshinProfile = `-- name: DeleteGenshinProfile :exec
DELETE FROM genshin_profiles WHERE id = $1
`

func (q *Queries) DeleteGenshinProfile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteGenshinProfile, id)
	return err
}

const editCharFromProfile = `-- name: EditCharFromProfile :one
WITH updated AS (
    UPDATE profile_chars
    SET
        level = $3, constellation = $4, talent_na = $5,
        talent_e = $6, talent_q = $7, notes = $8
    WHERE profile_chars.acc_id = $1 AND profile_chars.char_id = $2
    RETURNING acc_id, char_id, level, constellation, talent_na, talent_e, talent_q, notes
)
SELECT
    profile_chars.acc_id, profile_chars.char_id, profile_chars.level, profile_chars.constellation, profile_chars.talent_na, profile_chars.talent_e, profile_chars.talent_q, profile_chars.notes,
    char_details.id, char_details.name, char_details.element_id, char_details.stars, char_details.icon, char_details.notes, char_details.created_at, char_details.updated_at,
    elements.id, elements.name, elements.icon_url
FROM updated
JOIN profile_chars ON profile_chars.acc_id = updated.acc_id AND profile_chars.char_id = updated.char_id
JOIN char_details ON profile_chars.char_id = char_details.id
JOIN elements ON char_details.element_id = elements.id
`

type EditCharFromProfileParams struct {
	AccID         int64       `json:"acc_id"`
	CharID        int64       `json:"char_id"`
	Level         int16       `json:"level"`
	Constellation int16       `json:"constellation"`
	TalentNa      int16       `json:"talent_na"`
	TalentE       int16       `json:"talent_e"`
	TalentQ       int16       `json:"talent_q"`
	Notes         pgtype.Text `json:"notes"`
}

type EditCharFromProfileRow struct {
	ProfileChar ProfileChar `json:"profile_char"`
	CharDetail  CharDetail  `json:"char_detail"`
	Element     Element     `json:"element"`
}

func (q *Queries) EditCharFromProfile(ctx context.Context, arg EditCharFromProfileParams) (EditCharFromProfileRow, error) {
	row := q.db.QueryRow(ctx, editCharFromProfile,
		arg.AccID,
		arg.CharID,
		arg.Level,
		arg.Constellation,
		arg.TalentNa,
		arg.TalentE,
		arg.TalentQ,
		arg.Notes,
	)
	var i EditCharFromProfileRow
	err := row.Scan(
		&i.ProfileChar.AccID,
		&i.ProfileChar.CharID,
		&i.ProfileChar.Level,
		&i.ProfileChar.Constellation,
		&i.ProfileChar.TalentNa,
		&i.ProfileChar.TalentE,
		&i.ProfileChar.TalentQ,
		&i.ProfileChar.Notes,
		&i.CharDetail.ID,
		&i.CharDetail.Name,
		&i.CharDetail.ElementID,
		&i.CharDetail.Stars,
		&i.CharDetail.Icon,
		&i.CharDetail.Notes,
		&i.CharDetail.CreatedAt,
		&i.CharDetail.UpdatedAt,
		&i.Element.ID,
		&i.Element.Name,
		&i.Element.IconUrl,
	)
	return i, err
}

const editGenshinChar = `-- name: EditGenshinChar :one
WITH edited AS (
    UPDATE char_details
    SET
        name = $1,
        element_id = (SELECT id FROM elements WHERE elements.name = $2),
        stars = $3,
        icon = $4,
        notes = $5
    WHERE char_details.id = $6
    RETURNING id, name, element_id, stars, icon, notes, created_at, updated_at
)
SELECT edited.id, edited.name, edited.element_id, edited.stars, edited.icon, edited.notes, edited.created_at, edited.updated_at, elements.name AS element_name
from edited
JOIN elements ON edited.element_id = elements.id
`

type EditGenshinCharParams struct {
	Name        string      `json:"name"`
	ElementName string      `json:"element_name"`
	Stars       int16       `json:"stars"`
	Icon        []byte      `json:"icon"`
	Notes       pgtype.Text `json:"notes"`
	ID          int64       `json:"id"`
}

type EditGenshinCharRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	ElementID   int16              `json:"element_id"`
	Stars       int16              `json:"stars"`
	Icon        []byte             `json:"icon"`
	Notes       pgtype.Text        `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ElementName string             `json:"element_name"`
}

func (q *Queries) EditGenshinChar(ctx context.Context, arg EditGenshinCharParams) (EditGenshinCharRow, error) {
	row := q.db.QueryRow(ctx, editGenshinChar,
		arg.Name,
		arg.ElementName,
		arg.Stars,
		arg.Icon,
		arg.Notes,
		arg.ID,
	)
	var i EditGenshinCharRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ElementID,
		&i.Stars,
		&i.Icon,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ElementName,
	)
	return i, err
}

const editGenshinProfile = `-- name: EditGenshinProfile :one
UPDATE genshin_profiles
SET 
    name = $2,
    notes = $3
WHERE id = $1
RETURNING id, name, notes, created_at, updated_at
`

type EditGenshinProfileParams struct {
	ID    int64       `json:"id"`
	Name  string      `json:"name"`
	Notes pgtype.Text `json:"notes"`
}

func (q *Queries) EditGenshinProfile(ctx context.Context, arg EditGenshinProfileParams) (GenshinProfile, error) {
	row := q.db.QueryRow(ctx, editGenshinProfile, arg.ID, arg.Name, arg.Notes)
	var i GenshinProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllCharsFromProfile = `-- name: GetAllCharsFromProfile :many
SELECT
    profile_chars.acc_id, profile_chars.char_id, profile_chars.level, profile_chars.constellation, profile_chars.talent_na, profile_chars.talent_e, profile_chars.talent_q, profile_chars.notes, 
    char_details.id, char_details.name, char_details.element_id, char_details.stars, char_details.icon, char_details.notes, char_details.created_at, char_details.updated_at, 
    elements.id, elements.name, elements.icon_url
FROM profile_chars
JOIN char_details ON profile_chars.char_id = char_details.id
JOIN elements ON char_details.element_id = elements.id
WHERE profile_chars.acc_id = $1
`

type GetAllCharsFromProfileRow struct {
	ProfileChar ProfileChar `json:"profile_char"`
	CharDetail  CharDetail  `json:"char_detail"`
	Element     Element     `json:"element"`
}

func (q *Queries) GetAllCharsFromProfile(ctx context.Context, accID int64) ([]GetAllCharsFromProfileRow, error) {
	rows, err := q.db.Query(ctx, getAllCharsFromProfile, accID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCharsFromProfileRow
	for rows.Next() {
		var i GetAllCharsFromProfileRow
		if err := rows.Scan(
			&i.ProfileChar.AccID,
			&i.ProfileChar.CharID,
			&i.ProfileChar.Level,
			&i.ProfileChar.Constellation,
			&i.ProfileChar.TalentNa,
			&i.ProfileChar.TalentE,
			&i.ProfileChar.TalentQ,
			&i.ProfileChar.Notes,
			&i.CharDetail.ID,
			&i.CharDetail.Name,
			&i.CharDetail.ElementID,
			&i.CharDetail.Stars,
			&i.CharDetail.Icon,
			&i.CharDetail.Notes,
			&i.CharDetail.CreatedAt,
			&i.CharDetail.UpdatedAt,
			&i.Element.ID,
			&i.Element.Name,
			&i.Element.IconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllElements = `-- name: GetAllElements :many
SELECT id, name, icon_url FROM elements
`

func (q *Queries) GetAllElements(ctx context.Context) ([]Element, error) {
	rows, err := q.db.Query(ctx, getAllElements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Element
	for rows.Next() {
		var i Element
		if err := rows.Scan(&i.ID, &i.Name, &i.IconUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllGenshinChars = `-- name: GetAllGenshinChars :many
SELECT char_details.id, char_details.name, char_details.element_id, char_details.stars, char_details.icon, char_details.notes, char_details.created_at, char_details.updated_at, elements.name AS element_name
FROM char_details
JOIN elements ON char_details.element_id = elements.id
`

type GetAllGenshinCharsRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	ElementID   int16              `json:"element_id"`
	Stars       int16              `json:"stars"`
	Icon        []byte             `json:"icon"`
	Notes       pgtype.Text        `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ElementName string             `json:"element_name"`
}

func (q *Queries) GetAllGenshinChars(ctx context.Context) ([]GetAllGenshinCharsRow, error) {
	rows, err := q.db.Query(ctx, getAllGenshinChars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllGenshinCharsRow
	for rows.Next() {
		var i GetAllGenshinCharsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ElementID,
			&i.Stars,
			&i.Icon,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ElementName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getElementId = `-- name: GetElementId :one
SELECT id from elements WHERE name = $1
`

func (q *Queries) GetElementId(ctx context.Context, name string) (int16, error) {
	row := q.db.QueryRow(ctx, getElementId, name)
	var id int16
	err := row.Scan(&id)
	return id, err
}

const getProfiles = `-- name: GetProfiles :one
SELECT id, name, notes, created_at, updated_at FROM genshin_profiles WHERE id = $1
`

func (q *Queries) GetProfiles(ctx context.Context, id int64) (GenshinProfile, error) {
	row := q.db.QueryRow(ctx, getProfiles, id)
	var i GenshinProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
