// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hylscraper.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addHylComment = `-- name: AddHylComment :one
INSERT INTO hyl_comments (session_id, post_id, parent_comment_id, url, author, content) 
    VALUES ($1, $2, $3, $4, $5, $6)
    RETURNING id, session_id, post_id, parent_comment_id, url, author, content, created_at, updated_at
`

type AddHylCommentParams struct {
	SessionID       int64       `json:"session_id"`
	PostID          int64       `json:"post_id"`
	ParentCommentID pgtype.Int8 `json:"parent_comment_id"`
	Url             string      `json:"url"`
	Author          string      `json:"author"`
	Content         string      `json:"content"`
}

func (q *Queries) AddHylComment(ctx context.Context, arg AddHylCommentParams) (HylComment, error) {
	row := q.db.QueryRow(ctx, addHylComment,
		arg.SessionID,
		arg.PostID,
		arg.ParentCommentID,
		arg.Url,
		arg.Author,
		arg.Content,
	)
	var i HylComment
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PostID,
		&i.ParentCommentID,
		&i.Url,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addHylPost = `-- name: AddHylPost :one
INSERT INTO hyl_posts (session_id, url, author, title, content) 
    VALUES ($1, $2, $3, $4, $5)
    RETURNING id, session_id, url, author, title, content, created_at, updated_at
`

type AddHylPostParams struct {
	SessionID int64  `json:"session_id"`
	Url       string `json:"url"`
	Author    string `json:"author"`
	Title     string `json:"title"`
	Content   string `json:"content"`
}

func (q *Queries) AddHylPost(ctx context.Context, arg AddHylPostParams) (HylPost, error) {
	row := q.db.QueryRow(ctx, addHylPost,
		arg.SessionID,
		arg.Url,
		arg.Author,
		arg.Title,
		arg.Content,
	)
	var i HylPost
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Url,
		&i.Author,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHylScrapeSession = `-- name: CreateHylScrapeSession :one
INSERT INTO hyl_scrape_session (target, created_by_email)
    VALUES ($1, $2) RETURNING id, target, created_by_email, description, created_at, updated_at
`

type CreateHylScrapeSessionParams struct {
	Target         string `json:"target"`
	CreatedByEmail string `json:"created_by_email"`
}

func (q *Queries) CreateHylScrapeSession(ctx context.Context, arg CreateHylScrapeSessionParams) (HylScrapeSession, error) {
	row := q.db.QueryRow(ctx, createHylScrapeSession, arg.Target, arg.CreatedByEmail)
	var i HylScrapeSession
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.CreatedByEmail,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHylCommentByAuthor = `-- name: GetHylCommentByAuthor :many
SELECT id, session_id, post_id, parent_comment_id, url, author, content, created_at, updated_at FROM hyl_comments WHERE author = $1
`

func (q *Queries) GetHylCommentByAuthor(ctx context.Context, author string) ([]HylComment, error) {
	rows, err := q.db.Query(ctx, getHylCommentByAuthor, author)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HylComment
	for rows.Next() {
		var i HylComment
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PostID,
			&i.ParentCommentID,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHylCommentsAndPostsFromAuthor = `-- name: GetHylCommentsAndPostsFromAuthor :many
SELECT p.id, p.session_id, p.url, p.author, p.title, p.content, p.created_at, p.updated_at 
    FROM hyl_posts p
    WHERE p.author = $1
UNION
SELECT c.id, c.session_id, c.url, c.author, NULL::TEXT AS title, c.content, c.created_at, c.updated_at 
    FROM hyl_comments c
    WHERE c.author = $1
`

func (q *Queries) GetHylCommentsAndPostsFromAuthor(ctx context.Context, author string) ([]HylPost, error) {
	rows, err := q.db.Query(ctx, getHylCommentsAndPostsFromAuthor, author)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HylPost
	for rows.Next() {
		var i HylPost
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Url,
			&i.Author,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHylPostByAuthor = `-- name: GetHylPostByAuthor :many
SELECT id, session_id, url, author, title, content, created_at, updated_at FROM hyl_posts WHERE author = $1
`

func (q *Queries) GetHylPostByAuthor(ctx context.Context, author string) ([]HylPost, error) {
	rows, err := q.db.Query(ctx, getHylPostByAuthor, author)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HylPost
	for rows.Next() {
		var i HylPost
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Url,
			&i.Author,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHylPostsBySession = `-- name: GetHylPostsBySession :many
SELECT id, session_id, url, author, title, content, created_at, updated_at FROM hyl_posts WHERE session_id = $1
`

func (q *Queries) GetHylPostsBySession(ctx context.Context, sessionID int64) ([]HylPost, error) {
	rows, err := q.db.Query(ctx, getHylPostsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HylPost
	for rows.Next() {
		var i HylPost
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Url,
			&i.Author,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHylScrapeSessionByEmail = `-- name: GetHylScrapeSessionByEmail :many
SELECT id, target, created_by_email, description, created_at, updated_at FROM hyl_scrape_session WHERE created_by_email = $1
`

func (q *Queries) GetHylScrapeSessionByEmail(ctx context.Context, createdByEmail string) ([]HylScrapeSession, error) {
	rows, err := q.db.Query(ctx, getHylScrapeSessionByEmail, createdByEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HylScrapeSession
	for rows.Next() {
		var i HylScrapeSession
		if err := rows.Scan(
			&i.ID,
			&i.Target,
			&i.CreatedByEmail,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHylScrapeSessionById = `-- name: GetHylScrapeSessionById :one
SELECT id, target, created_by_email, description, created_at, updated_at FROM hyl_scrape_session WHERE id = $1
`

func (q *Queries) GetHylScrapeSessionById(ctx context.Context, id int64) (HylScrapeSession, error) {
	row := q.db.QueryRow(ctx, getHylScrapeSessionById, id)
	var i HylScrapeSession
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.CreatedByEmail,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
