// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (img_data, img_hash, added_by, filename, fileext) VALUES ($1, $2, $3, $4, $5) RETURNING id, img_data, img_hash, created_at, updated_at, added_by, filename, fileext, is_protected
`

type CreateImageParams struct {
	ImgData  []byte      `json:"img_data"`
	ImgHash  string      `json:"img_hash"`
	AddedBy  pgtype.Text `json:"added_by"`
	Filename string      `json:"filename"`
	Fileext  string      `json:"fileext"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.ImgData,
		arg.ImgHash,
		arg.AddedBy,
		arg.Filename,
		arg.Fileext,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ImgData,
		&i.ImgHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AddedBy,
		&i.Filename,
		&i.Fileext,
		&i.IsProtected,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteImage, id)
	return err
}

const getImageById = `-- name: GetImageById :one
SELECT id, img_data, img_hash, created_at, updated_at, added_by, filename, fileext, is_protected FROM images WHERE id = $1
`

func (q *Queries) GetImageById(ctx context.Context, id int64) (Image, error) {
	row := q.db.QueryRow(ctx, getImageById, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ImgData,
		&i.ImgHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AddedBy,
		&i.Filename,
		&i.Fileext,
		&i.IsProtected,
	)
	return i, err
}

const getImages = `-- name: GetImages :many
SELECT id, img_data, img_hash, created_at, updated_at, added_by, filename, fileext, is_protected FROM images
`

func (q *Queries) GetImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.Query(ctx, getImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.ImgData,
			&i.ImgHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AddedBy,
			&i.Filename,
			&i.Fileext,
			&i.IsProtected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
