// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	json "encoding/json"
	"github.com/jackc/pgx/v5/pgtype"
)

type Bingo struct {
	ID             int64              `json:"id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Cells          json.RawMessage    `json:"cells"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ImgCenter      pgtype.Int8        `json:"img_center"`
	ImgBg          pgtype.Int8        `json:"img_bg"`
	CardImgPreview []byte             `json:"card_img_preview"`
}

type Image struct {
	ID        int64              `json:"id"`
	ImgData   []byte             `json:"img_data"`
	ImgHash   string             `json:"img_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
