// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddCharToProfile(ctx context.Context, arg AddCharToProfileParams) (AddCharToProfileRow, error)
	AddHylComment(ctx context.Context, arg AddHylCommentParams) (HylComment, error)
	AddHylPost(ctx context.Context, arg AddHylPostParams) (HylPost, error)
	CreateBingo(ctx context.Context, arg CreateBingoParams) (Bingo, error)
	CreateGenshinChar(ctx context.Context, arg CreateGenshinCharParams) (CreateGenshinCharRow, error)
	CreateGenshinProfile(ctx context.Context, arg CreateGenshinProfileParams) (GenshinProfile, error)
	CreateHylScrapeSession(ctx context.Context, arg CreateHylScrapeSessionParams) (HylScrapeSession, error)
	CreateImage(ctx context.Context, arg CreateImageParams) (Image, error)
	DeleteBingo(ctx context.Context, id int64) error
	DeleteCharFromProfile(ctx context.Context, arg DeleteCharFromProfileParams) error
	DeleteGenshinChar(ctx context.Context, id int64) error
	DeleteGenshinProfile(ctx context.Context, id int64) error
	DeleteImage(ctx context.Context, id int64) error
	EditCharFromProfile(ctx context.Context, arg EditCharFromProfileParams) (EditCharFromProfileRow, error)
	EditGenshinChar(ctx context.Context, arg EditGenshinCharParams) (EditGenshinCharRow, error)
	EditGenshinProfile(ctx context.Context, arg EditGenshinProfileParams) (GenshinProfile, error)
	GetAllCharsFromProfile(ctx context.Context, profID int64) ([]GetAllCharsFromProfileRow, error)
	GetAllElements(ctx context.Context) ([]Element, error)
	GetAllGenshinChars(ctx context.Context) ([]GetAllGenshinCharsRow, error)
	GetBingo(ctx context.Context) ([]Bingo, error)
	GetBingoByEmail(ctx context.Context, createdByEmail pgtype.Text) ([]Bingo, error)
	GetBingoById(ctx context.Context, id int64) (Bingo, error)
	GetElementIconByName(ctx context.Context, name string) (pgtype.Text, error)
	GetElementId(ctx context.Context, name string) (int16, error)
	GetGenshinChar(ctx context.Context, id int64) (GetGenshinCharRow, error)
	GetHylCommentByAuthor(ctx context.Context, author string) ([]HylComment, error)
	GetHylCommentsAndPostsFromAuthor(ctx context.Context, author string) ([]HylPost, error)
	GetHylPostByAuthor(ctx context.Context, author string) ([]HylPost, error)
	GetHylPostsBySession(ctx context.Context, sessionID int64) ([]HylPost, error)
	GetHylScrapeSessionByEmail(ctx context.Context, createdByEmail string) ([]HylScrapeSession, error)
	GetHylScrapeSessionById(ctx context.Context, id int64) (HylScrapeSession, error)
	GetImageByHash(ctx context.Context, imgHash string) (Image, error)
	GetImageById(ctx context.Context, id int64) (Image, error)
	GetImages(ctx context.Context) ([]Image, error)
	GetProfile(ctx context.Context, id int64) (GenshinProfile, error)
	GetProfileCharStats(ctx context.Context, id int64) (int32, error)
	GetProfileElementCounts(ctx context.Context, profID int64) ([]GetProfileElementCountsRow, error)
	GetProfiles(ctx context.Context) ([]GenshinProfile, error)
	UpdateBingo(ctx context.Context, arg UpdateBingoParams) (Bingo, error)
}

var _ Querier = (*Queries)(nil)
