// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	json "encoding/json"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBingo = `-- name: CreateBingo :one
INSERT INTO bingo (title, description, cells) VALUES ($1, $2, $3) RETURNING id, title, description, cells, created_at, updated_at, img_center, img_bg, card_img_preview
`

type CreateBingoParams struct {
	Title       string          `json:"title"`
	Description pgtype.Text     `json:"description"`
	Cells       json.RawMessage `json:"cells"`
}

func (q *Queries) CreateBingo(ctx context.Context, arg CreateBingoParams) (Bingo, error) {
	row := q.db.QueryRow(ctx, createBingo, arg.Title, arg.Description, arg.Cells)
	var i Bingo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Cells,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImgCenter,
		&i.ImgBg,
		&i.CardImgPreview,
	)
	return i, err
}

const createImage = `-- name: CreateImage :one
INSERT INTO images (img_data, img_hash) VALUES ($1, $2) RETURNING id, img_data, img_hash, created_at, updated_at
`

type CreateImageParams struct {
	ImgData []byte `json:"img_data"`
	ImgHash string `json:"img_hash"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage, arg.ImgData, arg.ImgHash)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ImgData,
		&i.ImgHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBingo = `-- name: DeleteBingo :exec
DELETE FROM bingo WHERE id = $1
`

func (q *Queries) DeleteBingo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBingo, id)
	return err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteImage, id)
	return err
}

const getBingo = `-- name: GetBingo :many
SELECT id, title, description, cells, created_at, updated_at, img_center, img_bg, card_img_preview FROM bingo
`

func (q *Queries) GetBingo(ctx context.Context) ([]Bingo, error) {
	rows, err := q.db.Query(ctx, getBingo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bingo
	for rows.Next() {
		var i Bingo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Cells,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImgCenter,
			&i.ImgBg,
			&i.CardImgPreview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBingoById = `-- name: GetBingoById :one
SELECT id, title, description, cells, created_at, updated_at, img_center, img_bg, card_img_preview FROM bingo WHERE id = $1
`

func (q *Queries) GetBingoById(ctx context.Context, id int64) (Bingo, error) {
	row := q.db.QueryRow(ctx, getBingoById, id)
	var i Bingo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Cells,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImgCenter,
		&i.ImgBg,
		&i.CardImgPreview,
	)
	return i, err
}

const getImage = `-- name: GetImage :one
SELECT img_data FROM images WHERE id = $1
`

func (q *Queries) GetImage(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getImage, id)
	var img_data []byte
	err := row.Scan(&img_data)
	return img_data, err
}

const updateBingo = `-- name: UpdateBingo :one
UPDATE bingo SET title = $2, description = $3, cells = $4 WHERE id = $1 RETURNING id, title, description, cells, created_at, updated_at, img_center, img_bg, card_img_preview
`

type UpdateBingoParams struct {
	ID          int64           `json:"id"`
	Title       string          `json:"title"`
	Description pgtype.Text     `json:"description"`
	Cells       json.RawMessage `json:"cells"`
}

func (q *Queries) UpdateBingo(ctx context.Context, arg UpdateBingoParams) (Bingo, error) {
	row := q.db.QueryRow(ctx, updateBingo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Cells,
	)
	var i Bingo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Cells,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImgCenter,
		&i.ImgBg,
		&i.CardImgPreview,
	)
	return i, err
}
