// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateBingo(ctx context.Context, arg CreateBingoParams) (Bingo, error)
	CreateImage(ctx context.Context, arg CreateImageParams) (Image, error)
	DeleteBingo(ctx context.Context, id int64) error
	DeleteImage(ctx context.Context, id int64) error
	GetBingo(ctx context.Context) ([]Bingo, error)
	GetBingoById(ctx context.Context, id int64) (Bingo, error)
	GetImageById(ctx context.Context, id int64) ([]byte, error)
	GetImages(ctx context.Context) ([]Image, error)
	UpdateBingo(ctx context.Context, arg UpdateBingoParams) (Bingo, error)
}

var _ Querier = (*Queries)(nil)
